backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "siteIdentity"
    label: "Site Identity"
    folder: "src/content/site-identity"
    create: true
    delete: false
    slug: "site-identity"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
  - name: "hero"
    label: "Hero"
    folder: "src/content/hero"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Subheading", name: "subheading", widget: "string" }
      - { label: "Background", name: "background", widget: "image" }
  - name: "about"
    label: "About Us"
    folder: "src/content/about"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "object"
        summary: "{{fields.image}}"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "string" }
          - label: "Position"
            name: "position"
            widget: "select"
            options:
              - { label: "Left", value: "left" }
              - { label: "Right", value: "right" }
      - label: "Paragraphs"
        name: "paragraphs"
        widget: "list"
        summary: "{{fields.content}}"
        field: { label: "Content", name: "content", widget: "string" }
      - label: "Why Choose Us list"
        name: "whyChooseUsList"
        widget: "list"
        summary: "{{fields.whyChooseUsListItem}}"
        field:
          {
            label: "Why Choose Us list item",
            name: "whyChooseUsListItem",
            widget: "string",
          }
  - name: "car"
    label: "Car"
    folder: "src/content/cars"
    create: true
    slug: "{{fields.title}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Used to help you identify exact item you are looking for and as a part of URL (preferably unique).",
        }
      - { label: "Make", name: "make", widget: "string" }
      - { label: "Model", name: "model", widget: "string" }
      - { label: "Model Year", name: "modelYear", widget: "number" }
      - { label: "Mileage", name: "mileage", widget: "number" }
      - { label: "Engine Size cm3", name: "engineSize", widget: "number" }
      - label: "Transmission"
        name: "transmission"
        widget: "select"
        options:
          - { label: "Automatic", value: "Automatic" }
          - { label: "Manual", value: "Manual" }
      - label: "Fuel Type"
        name: "fuel"
        widget: "select"
        options:
          - { label: "Petrol", value: "Petrol" }
          - { label: "Electric", value: "Electric" }
          - { label: "Diesel", value: "Diesel" }
          - { label: "Hybrid", value: "Hybrid" }
      - { label: "Number of Seats", name: "seats", widget: "number" }
      - { label: "Price Per Day", name: "price", widget: "number" }
      - { label: "Featured Photo", name: "thumbnail", widget: "image" }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: "Image", name: "image", widget: "image" }
  - name: "featuredCars"
    label: "Featured Cars"
    folder: "src/content/featured-cars"
    create: true
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Bestsellers"
        name: "bestsellers"
        widget: "relation"
        multiple: true
        min: 3
        collection: "car"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
      - label: "New Cars"
        name: "newCars"
        widget: "relation"
        multiple: true
        min: 3
        collection: "car"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
  - name: "servicesAndFeatures"
    label: "Services And Features"
    folder: "src/content/services-and-features"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Services List"
        name: "servicesList"
        widget: "list"
        summary: "{{fields.serviceHeading}}"
        fields:
          - {
              label: "Service Heading",
              name: "serviceHeading",
              widget: "string",
            }
          - {
              label: "Service Description",
              name: "serviceDescription",
              widget: "string",
            }
