backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "hero"
    label: "Hero"
    folder: "src/content/hero"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Subheading", name: "subheading", widget: "string" }
  - name: "car"
    label: "Car"
    folder: "src/content/cars"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Used to help you identify exact item you are looking for and as a part of URL",
        }
      - { label: "Make", name: "make", widget: "string" }
      - { label: "Model", name: "model", widget: "string" }
      - { label: "Model Year", name: "modelYear", widget: "number" }
      - { label: "Mileage", name: "mileage", widget: "number" }
      - { label: "Engine Size cm3", name: "engineSize", widget: "number" }
      - label: "Transmission"
        name: "transmission"
        widget: "select"
        options:
          - { label: "Automatic", value: "Automatic" }
          - { label: "Manual", value: "Manual" }
      - { label: "Price Per Day", name: "price", widget: "number" }
      - { label: "Featured Photo", name: "thumbnail", widget: "image" }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: "Image", name: "image", widget: "image" }
